version: "3.9"

services:

  # -------------------------------
  # PostgreSQL (n8n persistence)
  # -------------------------------
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: n8n-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 30s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

    logging:
      driver: journald
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - "127.0.0.1:5434:5432"


  # -------------------------------
  # n8n (workflow orchestration)
  # -------------------------------
  n8n:
    image: docker.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      # Database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      # Runtime
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      NODE_ENV: production
      GENERIC_TIMEZONE: UTC

      # Execution data retention
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: "none"
      EXECUTIONS_DATA_SAVE_ON_ERROR: "all"
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: 168

    volumes:
      - n8n_data:/home/node/.n8n

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

    logging:
      driver: journald
      options:
        max-size: "20m"
        max-file: "3"

    ports:
      - "127.0.0.1:5678:5678"


  # -------------------------------
  # Python Runtime (automation / compute)
  # -------------------------------
  python-runtime:
    image: automation-python:latest   # custom image, built later
    container_name: python-runtime
    restart: unless-stopped

    environment:
      PYTHONUNBUFFERED: "1"
      TZ: UTC

    volumes:
      - python_data:/app/data

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

    logging:
      driver: journald
      options:
        max-size: "20m"
        max-file: "3"

    ports:
      - "127.0.0.1:8000:8000"


  # -------------------------------
  # Hook0 (webhook gateway) — DISABLED
  # -------------------------------
  # hook0:
  #   image: docker.io/hook0/hook0:latest
  #   container_name: hook0
  #   restart: unless-stopped
  #
  #   env_file:
  #     - .env
  #
  #   volumes:
  #     - hook0_data:/data
  #
  #   healthcheck:
  #     test: ["CMD-SHELL", "wget -qO- http://localhost:8085/health || exit 1"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 5
  #
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 512M
  #
  #   logging:
  #     driver: journald
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #
  #   ports:
  #     - "127.0.0.1:8085:8085"


volumes:
  n8n_postgres_data:
  n8n_data:
  python_data:
  # hook0_data:
