services:

  # -------------------------------
  # PostgreSQL (n8n persistence)
  # -------------------------------
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: n8n-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data

    ports:
      - "127.0.0.1:5434:5432"


  # -------------------------------
  # n8n (workflow orchestration)
  # -------------------------------
  n8n:
    build:
      context: ../n8n
      dockerfile: Dockerfile
    image: automation-n8n:latest
    container_name: n8n
    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      NODE_ENV: production
      GENERIC_TIMEZONE: UTC

      EXECUTIONS_DATA_SAVE_ON_SUCCESS: "none"
      EXECUTIONS_DATA_SAVE_ON_ERROR: "all"
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: 168

    volumes:
      - n8n_data:/home/node/.n8n

    ports:
      - "192.168.1.9:5678:5678"



  # -------------------------------
  # Python Runtime (automation / compute)
  # -------------------------------
  python-runtime:
    build:
      context: ../python
      dockerfile: Dockerfile
    image: automation-python:latest
    container_name: python-runtime
    restart: unless-stopped

    environment:
      PYTHONUNBUFFERED: "1"
      TZ: UTC

    volumes:
      - python_data:/app/data

    ports:
      - "127.0.0.1:8000:8000"



  # -------------------------------
  # Hook0 (webhook gateway) — DISABLED
  # -------------------------------
  # hook0:
  #   image: docker.io/hook0/hook0:latest
  #   container_name: hook0
  #   restart: unless-stopped
  #
  #   env_file:
  #     - .env
  #
  #   volumes:
  #     - hook0_data:/data
  #
  #   healthcheck:
  #     test: ["CMD-SHELL", "wget -qO- http://localhost:8085/health || exit 1"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 5
  #
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 512M
  #
  #   logging:
  #     driver: journald
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #
  #   ports:
  #     - "127.0.0.1:8085:8085"


volumes:
  n8n_postgres_data:
  n8n_data:
  python_data:
  # hook0_data:
